import type { OceanFreightRate } from '@/lib/types/finance';

export const MOCK_OCEAN_FREIGHT: OceanFreightRate[] = [
    {
        id: 'of-1',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'lon',
        destinationCountry: 'UK',
        destinationPort: 'London Gateway',
        destinationPortCode: 'GBLON',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 4606.00,
        bafUSD: 882.00,
        ispsUSD: 15.00,
        rcgUSD: 42.00,
        otherSurchargesUSD: 55.00,
        totalUSD: 5600.00,
        exchangeRate: 15.9,
        totalZAR: 89040.00,
        active: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-2',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'imm',
        destinationCountry: 'UK',
        destinationPort: 'Immingham',
        destinationPortCode: 'GBIMM',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 0,
        bafUSD: 0,
        ispsUSD: 0,
        rcgUSD: 0,
        otherSurchargesUSD: 0,
        totalUSD: 0,
        exchangeRate: 0,
        totalZAR: 0,
        active: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-3',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'dub',
        destinationCountry: 'Ireland',
        destinationPort: 'Dublin',
        destinationPortCode: 'IEDUB',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 3900.00,
        bafUSD: 882.00,
        ispsUSD: 15.00,
        rcgUSD: 42.00,
        otherSurchargesUSD: 859.00,
        totalUSD: 5698.00,
        exchangeRate: 15.9,
        totalZAR: 90598.20,
        active: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-4',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'lex',
        destinationCountry: 'Portugal',
        destinationPort: 'Leixões',
        destinationPortCode: 'PTLEI',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 3950.00,
        bafUSD: 884.00,
        ispsUSD: 15.00,
        rcgUSD: 42.00,
        otherSurchargesUSD: 157.00,
        totalUSD: 5048.00,
        exchangeRate: 15.9,
        totalZAR: 80263.20,
        active: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-5',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'goa',
        destinationCountry: 'Italy',
        destinationPort: 'Genoa',
        destinationPortCode: 'ITGOA',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 3700.00,
        bafUSD: 882.00,
        ispsUSD: 15.00,
        rcgUSD: 42.00,
        otherSurchargesUSD: 11.00,
        totalUSD: 4650.00,
        exchangeRate: 15.9,
        totalZAR: 73935.00,
        active: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-6',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'anr',
        destinationCountry: 'Belgium',
        destinationPort: 'Antwerp',
        destinationPortCode: 'BEANR',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 0,
        bafUSD: 0,
        ispsUSD: 0,
        rcgUSD: 0,
        otherSurchargesUSD: 0,
        totalUSD: 0,
        exchangeRate: 0,
        totalZAR: 0,
        active: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-7',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'brv',
        destinationCountry: 'Germany',
        destinationPort: 'Bremerhaven',
        destinationPortCode: 'DEBRV',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 0,
        bafUSD: 0,
        ispsUSD: 0,
        rcgUSD: 0,
        otherSurchargesUSD: 0,
        totalUSD: 0,
        exchangeRate: 0,
        totalZAR: 0,
        active: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-8',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'leh',
        destinationCountry: 'France',
        destinationPort: 'Le Havre',
        destinationPortCode: 'FRLEH',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 3900.00,
        bafUSD: 882.00,
        ispsUSD: 15.00,
        rcgUSD: 42.00,
        otherSurchargesUSD: 329.00,
        totalUSD: 5168.00,
        exchangeRate: 15.9,
        totalZAR: 82171.20,
        active: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-9',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'vgo',
        destinationCountry: 'Spain',
        destinationPort: 'Vigo',
        destinationPortCode: 'ESVGO',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 0,
        bafUSD: 0,
        ispsUSD: 0,
        rcgUSD: 0,
        otherSurchargesUSD: 0,
        totalUSD: 0,
        exchangeRate: 0,
        totalZAR: 0,
        active: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-10',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'lms',
        destinationCountry: 'Cyprus',
        destinationPort: 'Limassol',
        destinationPortCode: 'CYLMS',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 6168.00,
        bafUSD: 882.00,
        ispsUSD: 15.00,
        rcgUSD: 42.00,
        otherSurchargesUSD: 1739.00,
        totalUSD: 8846.00,
        exchangeRate: 15.9,
        totalZAR: 140651.40,
        active: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'of-11',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        origin: 'Cape Town/Durban',
        originCode: 'ZACPT',
        destinationId: 'lpa',
        destinationCountry: 'Spain',
        destinationPort: 'Las Palmas',
        destinationPortCode: 'ESLPA',
        shippingLine: 'MSC',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        freightUSD: 0,
        bafUSD: 0,
        ispsUSD: 0,
        rcgUSD: 0,
        otherSurchargesUSD: 0,
        totalUSD: 0,
        exchangeRate: 0,
        totalZAR: 0,
        active: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    }
];

export function getOceanFreightById(id: string): OceanFreightRate | undefined {
    return MOCK_OCEAN_FREIGHT.find(of => of.id === id);
}

export function getOceanFreightByDestination(destinationId: string): OceanFreightRate[] {
    return MOCK_OCEAN_FREIGHT.filter(of => of.destinationId === destinationId);
}

export function getOceanFreightByCountry(country: string): OceanFreightRate[] {
    return MOCK_OCEAN_FREIGHT.filter(of => of.destinationCountry === country);
}

export function getActiveOceanFreight(): OceanFreightRate[] {
    return MOCK_OCEAN_FREIGHT.filter(of => of.active);
}
