import type { OriginCharge, OriginChargeItem } from '@/lib/types/finance';

// Mock Origin Charge Items for Cape Town -> 40ft HC Reefer -> SRS
// Updated to match user screenshot values
const CPT_40HC_SRS_ITEMS: OriginChargeItem[] = [
    {
        id: 'oci-1',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'COLLECTION',
        chargeName: 'Collection in/around Cape Town',
        chargeType: 'PER_CONTAINER',
        category: 'COLLECTION',
        unitCost: null,
        containerCost: 10000.00,
        mandatory: true,
        sortOrder: 1,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-2',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'COLD_STORAGE',
        chargeName: 'Cold storage per week and part thereof',
        chargeType: 'PER_PALLET',
        category: 'STORAGE',
        unitCost: 335.00,
        containerCost: 6700.00,
        mandatory: true,
        sortOrder: 2,
        notes: 'Charged weekly, minimum 1 week',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-3',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'HANDLING',
        chargeName: 'Handling in and out',
        chargeType: 'PER_PALLET',
        category: 'HANDLING',
        unitCost: 130.00,
        containerCost: 2600.00,
        mandatory: true,
        sortOrder: 3,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-4',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'TRANSPORT_TBP',
        chargeName: 'Transport - Table Bay to port',
        chargeType: 'PER_PALLET',
        category: 'TRANSPORT',
        unitCost: 260.00,
        containerCost: 5200.00,
        mandatory: true,
        sortOrder: 4,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-5',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'FUEL_SURCHARGE',
        chargeName: 'Fuel Surcharge',
        chargeType: 'FIXED',
        category: 'TRANSPORT',
        unitCost: null,
        containerCost: null,
        mandatory: false,
        sortOrder: 5,
        notes: 'Subject to change based on fuel prices',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-6',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'GENSET',
        chargeName: 'Genset',
        chargeType: 'PER_PALLET',
        category: 'TRANSPORT',
        unitCost: 92.50,
        containerCost: 1850.00,
        mandatory: true,
        sortOrder: 6,
        notes: 'Refrigeration power unit',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-7',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'VGM',
        chargeName: 'VGM (Verified Gross Mass)',
        chargeType: 'PER_PALLET',
        category: 'REGULATORY',
        unitCost: 45.00,
        containerCost: 900.00,
        mandatory: true,
        sortOrder: 7,
        notes: 'SOLAS requirement',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-8',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'THC',
        chargeName: 'Terminal Handling Charge',
        chargeType: 'PER_CONTAINER',
        category: 'REGULATORY',
        unitCost: 309.40,
        containerCost: 6188.00,
        mandatory: true,
        sortOrder: 8,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-9',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'CARRIER_SVC',
        chargeName: 'Carrier Service Fee',
        chargeType: 'PER_PALLET',
        category: 'REGULATORY',
        unitCost: 72.35,
        containerCost: 1447.00,
        mandatory: true,
        sortOrder: 9,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-10',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'CARGO_DUES',
        chargeName: 'Cargo Dues',
        chargeType: 'PER_CONTAINER',
        category: 'REGULATORY',
        unitCost: null,
        containerCost: 826.67,
        mandatory: true,
        sortOrder: 10,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-11',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'BL_FEE',
        chargeName: 'Bill of Lading Fee',
        chargeType: 'PER_CONTAINER',
        category: 'DOCUMENTATION',
        unitCost: null,
        containerCost: 5500.00,
        mandatory: true,
        sortOrder: 11,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-12',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'SEAL_FEE',
        chargeName: 'Seal Fee',
        chargeType: 'PER_CONTAINER',
        category: 'REGULATORY',
        unitCost: null,
        containerCost: 350.00,
        mandatory: true,
        sortOrder: 12,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-13',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'NAVIS',
        chargeName: 'Navis Fee',
        chargeType: 'PER_CONTAINER',
        category: 'REGULATORY',
        unitCost: null,
        containerCost: 350.00,
        mandatory: true,
        sortOrder: 13,
        notes: 'Port system fee',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-14',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'COURIER',
        chargeName: 'Courier Fee',
        chargeType: 'PER_CONTAINER',
        category: 'DOCUMENTATION',
        unitCost: null,
        containerCost: 850.00,
        mandatory: true,
        sortOrder: 14,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-15',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'TRACKING',
        chargeName: 'Tracking and reporting',
        chargeType: 'PER_CONTAINER',
        category: 'DOCUMENTATION',
        unitCost: null,
        containerCost: 1750.00,
        mandatory: true,
        sortOrder: 15,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-16',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'DATA_LOGGER',
        chargeName: 'Data Logger',
        chargeType: 'PER_CONTAINER',
        category: 'DOCUMENTATION',
        unitCost: null,
        containerCost: 750.00,
        mandatory: true,
        sortOrder: 16,
        notes: 'TIVE temperature monitoring device',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-17',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'PORT_HEALTH',
        chargeName: 'Port Health Inspections',
        chargeType: 'PER_CONTAINER',
        category: 'REGULATORY',
        unitCost: null,
        containerCost: 1200.00,
        mandatory: true,
        sortOrder: 17,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-18',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'PPECB',
        chargeName: 'PPECB Inspection',
        chargeType: 'PER_CONTAINER',
        category: 'REGULATORY',
        unitCost: null,
        containerCost: 1850.00,
        mandatory: true,
        sortOrder: 18,
        notes: 'Perishable Products Export Control Board',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-19',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'EUR1',
        chargeName: 'EUR 1 Certificate',
        chargeType: 'PER_CONTAINER',
        category: 'REGULATORY',
        unitCost: null,
        containerCost: 350.00,
        mandatory: false,
        sortOrder: 19,
        notes: 'Certificate of origin for EU destinations',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-20',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'NRCS',
        chargeName: 'NRCS Inspection',
        chargeType: 'PER_CONTAINER',
        category: 'REGULATORY',
        unitCost: null,
        containerCost: 1500.00,
        mandatory: true,
        sortOrder: 20,
        notes: 'National Regulator for Compulsory Specifications',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-21',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'EDI',
        chargeName: 'EDI Fee',
        chargeType: 'PER_CONTAINER',
        category: 'REGULATORY',
        unitCost: null,
        containerCost: null,
        mandatory: true,
        sortOrder: 21,
        notes: 'Electronic Data Interchange',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-22',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'CUSTOMS',
        chargeName: 'Customs Clearance',
        chargeType: 'PER_CONTAINER',
        category: 'CUSTOMS',
        unitCost: null,
        containerCost: 1200.00,
        mandatory: true,
        sortOrder: 22,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-23',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'INSURANCE',
        chargeName: 'Insurance',
        chargeType: 'PER_CONTAINER',
        category: 'INSURANCE',
        unitCost: null,
        containerCost: 12000.00,
        mandatory: true,
        sortOrder: 23,
        notes: 'Optional cargo insurance',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-24',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'AGENCY_FEE',
        chargeName: 'Agency Fee',
        chargeType: 'PER_CONTAINER',
        category: 'OTHER',
        unitCost: null,
        containerCost: 8000.00,
        mandatory: true,
        sortOrder: 24,
        notes: null,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oci-25',
        originChargeId: 'oc-cpt-40hc-srs',
        chargeCode: 'FACILITY_FEE',
        chargeName: 'Facility Fee - on 30 days',
        chargeType: 'PER_CONTAINER',
        category: 'OTHER',
        unitCost: null,
        containerCost: 4500.00,
        mandatory: true,
        sortOrder: 25,
        notes: 'Warehouse facility usage',
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    }
];

export const MOCK_ORIGIN_CHARGES: OriginCharge[] = [
    {
        id: 'oc-cpt-40hc-srs',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        originId: 'cpt',
        originName: 'Cape Town',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        currency: 'ZAR',
        items: CPT_40HC_SRS_ITEMS,
        active: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oc-cpt-20ft-srs',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        originId: 'cpt',
        originName: 'Cape Town',
        containerId: '20ft-reefer-std',
        containerDisplayName: '20ft Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        currency: 'ZAR',
        items: [], // Simplified for brevity
        active: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    },
    {
        id: 'oc-dur-40hc-srs',
        salesRateTypeId: 'srs',
        salesRateTypeName: 'SRS',
        originId: 'dur',
        originName: 'Durban',
        containerId: '40ft-reefer-hc',
        containerDisplayName: '40ft HC Reefer',
        effectiveFrom: '2024-01-01',
        effectiveTo: '2024-12-31',
        currency: 'ZAR',
        items: [], // Similar structure to CPT
        active: true,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
    }
];

export function getOriginChargeById(id: string): OriginCharge | undefined {
    return MOCK_ORIGIN_CHARGES.find(oc => oc.id === id);
}

export function getOriginChargesByOrigin(originId: string): OriginCharge[] {
    return MOCK_ORIGIN_CHARGES.filter(oc => oc.originId === originId);
}

export function getOriginChargesByContainer(containerId: string): OriginCharge[] {
    return MOCK_ORIGIN_CHARGES.filter(oc => oc.containerId === containerId);
}

export function getActiveOriginCharges(): OriginCharge[] {
    return MOCK_ORIGIN_CHARGES.filter(oc => oc.active);
}
